### ISSUE TITLE
How to run EDIReader?

### ISSUE THREAD

**Issue by dhananjaygoel** [BerryWorksSoftware/edireader#10]
I want to install it on Ubuntu? How can I install this tool and process my EDI messages? Any guidance on this would be great.

**Comment by canabrook** [comment]
I can help with that.  Since this is a Java system, you first need to make sure that a Java JRE is installed on your Ubuntu machine. Any JRE version 8 or later should work just fine. From a command line, you can confirm this with the command "java -version". 

Next you need the edireader-5.4.15.jar (or later version). One is provided in the lib directory, or you can build your own using Maven and/or your favorite Java IDE. Then you can run the basic EDI to XML transformation with

$ java  -jar edireader-5.4.15.jar  <edi-file>  -o  <xml-file>

This and several other command line interface utility programs are in the com.berryworks.edireader.demo package.  You may, of course, use these simply as examples and use the Java API with your own Java programs.
