### ISSUE TITLE
Modify length parameters for ISA elements.

### ISSUE THREAD

**Issue by dhananjaygoel** [BerryWorksSoftware/edireader#11]
I have EDIx12 837 messages which has wrong length in ISA elements.

For ex. ISA03 should be minimum 10 characters, but in my message, it is only 3 characters.

How can I change the length properties?

**Comment by canabrook** [comment]
The ISA segment, unlike all other segments in X12, has fixed length fields for a variety of technical and historic reasons, so it is unusual indeed for an X12 interchange to be flawed in this way. Since the X12 parser in EDIReader pays close attention to the ISA to determine the specific syntax characters that are in play and to provide good error messages and recovery when things are flawed, it does not support an easy way to change these constants.

If you believe that your 837 sample represents a real use case that needs to be supported, please send me a copy of the ISA (not the entire 837 of course unless it contains only test data!) and I will consider ways to support this variant without sacrificing reliability.

**Comment by dhananjaygoel** [comment]
`ISA*00*NA *00*NA *ZZ*NA *ZZ*ABC *150415*1332*^*00701*000000001*0*T*:~`

**Comment by dhananjaygoel** [comment]
`ISA*00*NA *00*NA *ZZ*NA *ZZ*ABC *150415*1332*^*00701*000000001*0*T*:~`

**Comment by canabrook** [comment]
Thanks. As you say, several of the ISA fields are shorter than the expected fixed length. The version element 00701 suggests that this is perhaps from a sample from the new 7010 version of X12. The NA and ABC for the sender and receiver addresses indicate this is sample/test data instead of actual EDI data to be parsed. 

Here is the same ISA sample with periods added to pad the 4 fields to the proper length, which may help you continue with your testing. 
ISA*00*NA........*00*NA........*ZZ*NA.............*ZZ*ABC............*150415*1332*^*00701*000000001*0*T*:~

If you have reason to believe that the actual data *really* does/will not follow the fixed length requirements for these particular elements, let me know and I will look to modify the code to handle these elements as variable in length.

**Comment by canabrook** [comment]
I believe it will be fairly easy for me to allow these particular elements to be variable in length, without risking unintended consequences or adding excessive complexity. If everything goes smoothly, I would expect to have an update within a week.

If you happen to have the complete 837 7010 sample that is safe to share, I would like to have a copy for my testing.

**Comment by dhananjaygoel** [comment]
The message which I have are actual messages and I am afraid I won't be
able to share it.

Would be great to get this working asap.

**Comment by canabrook** [comment]
I understand. I will try hard to get this one done very quickly, maybe even within the next 12 hours. I am very interested in establishing EDIReader as a proven tool for handling the next generation of 837s and related transactions.

**Comment by dhananjaygoel** [comment]
Great, thanks.

**Comment by canabrook** [comment]
Release 5.4.16 is ready for you with the new feature.

**Comment by dhananjaygoel** [comment]
I ran the software. First I got this problem:

Output file output.xml opened
ERROR:  'Segment count error in SE segment. Expected 53 instead of 52 at segment 55, field 2'

Failure to transform: javax.xml.transform.TransformerException: com.berryworks.edireader.error.SegmentCountException: Segment count error in SE segment. Expected 53 instead of 52 at segment 55, field 2
com.berryworks.edireader.error.SegmentCountException: Segment count error in SE segment. Expected 53 instead of 52 at segment 55, field 2

I changed SE to 53 instead of 52, to make it work. It generated XML as per below:

![Screenshot 2019-03-23 at 10 50 59 PM](https://user-images.githubusercontent.com/2780489/54869432-3764f900-4dbe-11e9-890c-c19908b07a90.png)

However, there is no LOOP or element information. The XML is pretty much same as the text.

Is there a way to get the loop, element name information available?

**Comment by canabrook** [comment]
The error message that you received was simply reporting an error in your EDI input. As you noticed, the error was resolved by correcting your data. The Java API allows you to also handle such errors and continue parsing. 

Segment loops are detected and expressed in the XML with the aid of a plugin specific to the particular transaction type and version. Some plugins are included in the open source project. A full set of plugins are available in the full EDIReader Framework available with a commercial license.

**Comment by dhananjaygoel** [comment]
Is x12 837 included in the open source?

**Comment by canabrook** [comment]
Currently, no. Given the high interest in that particular one, I will commit to providing an 837 (version 5010) plugin in this open source Community Edition. I expect to have it added within a very few days. Then we can close out this issue!

**Comment by dhananjaygoel** [comment]
Sounds great. Also, can you lift the restriction for the above error of
value? Because I have 30K messages with the same problem. I don't want to
change the messages. The software should work no matter what the input is.

**Comment by canabrook** [comment]
I created a new issue to track the separate topic: How do you recover from EDI input with wrong segment count in SE trailer?  Fortunately, there is a nice answer with EDIReader. By the way, whatever software created these fundamentally flawed EDI transactions ought to be fixed.
