### ISSUE TITLE
Trailer Records in 835 not in JSON output

### ISSUE THREAD

**Issue by waldenrt** [BerryWorksSoftware/edireader#14]
Good Morning, I am using the community edition of the edireader and processing 835 messages to JSON.  I'm not seeing where the SE, GE or IEA segments are being written out.  Is that by design or is there an option we can enable to output those segments?

Thanks,

**Comment by canabrook** [comment]
This is by design. The SE, GE, and IEA segments are "structural" trailers in the EDI syntax that contain no business data. The EDI parser checks them to make sure they are correct, but does not express them directly in the XML our JSON output. In the other direction, EDIWriter automatically generates these trailer segments when producing EDI output from XML or JSON input.
